defaults:
  - _self_
  - model: minkloc_multimodal
  - dataset: nclt_multimodal
  - loss: contrastive_multimodal
  - optimizer: adam
  - scheduler: multi_step
  - general: multimodal

wandb:
  disabled: False
  project: OpenPlaceRecognition_test
  run_name: null
